rpm: fix string representation for flags
The `<rpm:requires>` xml tag entries had wrong string representation
for flags. Now it is implemented in the same way as it is done in the
rpm-software-management/createrepo_c project [1].

For instance,

    # working example entry
    <rpm:entry name="keyutils-libs" flags="GE" epoch="0" ver="1.5.8"/>

    # not working example entry
    <rpm:entry name="keyutils-libs" flags="GT" epoch="0" ver="1.5.8"/>

As a result, package manager could not resolve dependencies and failed
with the following error:

    Error: Package: krb5-libs-1.15.1-37.el7.x86_64 (local)
              Requires: keyutils-libs > 1.5.8
              Installed: keyutils-libs-1.5.8-3.el7.x86_64 (@CentOS)
                  keyutils-libs = 1.5.8-3.el7

[1] https://github.com/rpm-software-management/createrepo_c/blob/d8da644/src/misc.c#L51