rpm: escape special characters in XML
This patch makes special XML characters be escaped in the `provides`,
`requires`, and `obsoletes` sections to avoid the following error:

    xml.etree.ElementTree.ParseError: not well-formed (invalid token)

Note, commit c8ca21f7 (rpm: fix xml.etree.ElementTree.ParseError issue)
fixed the same issue but for the `license` section only.

Follows up #66